
package io.customer.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://customer.io")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param deleteCustomerDetailRequest
     * @return
     *     returns io.customer.client.DeleteCustomerDetailResponse
     */
    @WebMethod(operationName = "DeleteCustomerDetail")
    @WebResult(name = "DeleteCustomerDetailResponse", targetNamespace = "http://customer.io", partName = "DeleteCustomerDetailResponse")
    public DeleteCustomerDetailResponse deleteCustomerDetail(
        @WebParam(name = "DeleteCustomerDetailRequest", targetNamespace = "http://customer.io", partName = "DeleteCustomerDetailRequest")
        DeleteCustomerDetailRequest deleteCustomerDetailRequest);

    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns io.customer.client.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://customer.io", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://customer.io", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

    /**
     * 
     * @param getAllCustomerDetailRequest
     * @return
     *     returns io.customer.client.GetAllCustomerDetailResponse
     */
    @WebMethod(operationName = "GetAllCustomerDetail")
    @WebResult(name = "GetAllCustomerDetailResponse", targetNamespace = "http://customer.io", partName = "GetAllCustomerDetailResponse")
    public GetAllCustomerDetailResponse getAllCustomerDetail(
        @WebParam(name = "GetAllCustomerDetailRequest", targetNamespace = "http://customer.io", partName = "GetAllCustomerDetailRequest")
        GetAllCustomerDetailRequest getAllCustomerDetailRequest);

}
